### PR TITLE
Updated readme file

### PR DESCRIPTION
**Pull request by martinstofko219**
@demetrio812 I updated the readme file by removing the unnecessary android dependency line.

### CODE REVIEW

**Comment by demetrio812** [comment]
Hello, thanks for that, so there is no other recommendation on Android, correct?

**Comment by demetrio812** [comment]
(I'm asking because right now I can't test it with Android and I'd like to push it quickly)

**Comment by martinstofko219** [comment]
@demetrio812 I believe we're good now.

I noticed the crash due to the outdated dependency when I included the nativescript-plugin-firebase in an app I'm working on and tried to receive push notifications on Android. Since removing this dependency, the push notifications work correctly. I was able to verify this with an Android emulator, not an actual Android device since I don't have one at this time.

**Comment by martinstofko219** [comment]
@demetrio812 I also verified that the mixpanel tracking still works as expected for both iOS and Android as part of testing my app.

**Comment by martinstofko219** [comment]
@demetrio812 I have a quick update. My co-worker tested with a physical android device and all seems good. Is there any further work/research you'd like me to do on this?

**Comment by james-criscuolo** [comment]
I can confirm this works in a production environment. My company has been running this locally without the app.gradle line or the code removed in #8 for quite a while (over a year). I was trying to determine why it was never pushed back, and came up empty, but I hope once this releases to get back on the npm dependency (the only other diff seems to involve adding `productFlavors` to the `app.gradle` which I don't believe is necessary).

**Pull request merged**
